#!/usr/bin/env bash
# Configuration management

CONFIG_FILE="${SCRIPT_DIR}/config/installer.conf"

save_config() {
    log_info "Saving configuration to $CONFIG_FILE"
    mkdir -p "$(dirname "$CONFIG_FILE")"
    cat > "$CONFIG_FILE" << EOF
# Gentoo Installer v2.0 - User Configuration
# This file is automatically generated. Do not edit manually.

# System Configuration
CONFIG_INIT_SYSTEM="${CONFIG[INIT_SYSTEM]}"
CONFIG_BOOT_MODE="${CONFIG[BOOT_MODE]}"
CONFIG_HOSTNAME="${CONFIG[HOSTNAME]}"
CONFIG_USERNAME="${CONFIG[USERNAME]}"
CONFIG_TIMEZONE="${CONFIG[TIMEZONE]}"

# Disk Configuration
CONFIG_INSTALL_DISK="${CONFIG[INSTALL_DISK]}"
CONFIG_FILESYSTEM="${CONFIG[FILESYSTEM]}"
CONFIG_USE_ENCRYPTION="${CONFIG[USE_ENCRYPTION]}"

# Installation State
CONFIG_MOUNT_POINT="${CONFIG[MOUNT_POINT]}"
EOF
    log_success "Configuration saved"
}

load_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        log_info "Loading configuration from $CONFIG_FILE"
        source "$CONFIG_FILE"
        
        # Map loaded variables back to CONFIG array
        CONFIG[INIT_SYSTEM]="${CONFIG_INIT_SYSTEM:-}"
        CONFIG[BOOT_MODE]="${CONFIG_BOOT_MODE:-}"
        CONFIG[HOSTNAME]="${CONFIG_HOSTNAME:-${DEFAULT_HOSTNAME:-gentoo}}"
        CONFIG[USERNAME]="${CONFIG_USERNAME:-${DEFAULT_USERNAME:-user}}"
        CONFIG[TIMEZONE]="${CONFIG_TIMEZONE:-${DEFAULT_TIMEZONE:-UTC}}"
        CONFIG[INSTALL_DISK]="${CONFIG_INSTALL_DISK:-}"
        CONFIG[FILESYSTEM]="${CONFIG_FILESYSTEM:-}"
        CONFIG[USE_ENCRYPTION]="${CONFIG_USE_ENCRYPTION:-no}"
        CONFIG[MOUNT_POINT]="${CONFIG_MOUNT_POINT:-/mnt/gentoo}"
        
        log_success "Configuration loaded"
        return 0
    else
        log_info "No saved configuration found. Using defaults."
        # Set default values when no config exists
        CONFIG[INIT_SYSTEM]="${CONFIG_INIT_SYSTEM:-}"
        CONFIG[BOOT_MODE]="${CONFIG_BOOT_MODE:-}"
        CONFIG[HOSTNAME]="${CONFIG_HOSTNAME:-${DEFAULT_HOSTNAME:-gentoo}}"
        CONFIG[USERNAME]="${CONFIG_USERNAME:-${DEFAULT_USERNAME:-user}}"
        CONFIG[TIMEZONE]="${CONFIG_TIMEZONE:-${DEFAULT_TIMEZONE:-UTC}}"
        CONFIG[INSTALL_DISK]="${CONFIG_INSTALL_DISK:-}"
        CONFIG[FILESYSTEM]="${CONFIG_FILESYSTEM:-}"
        CONFIG[USE_ENCRYPTION]="${CONFIG_USE_ENCRYPTION:-no}"
        CONFIG[MOUNT_POINT]="${CONFIG_MOUNT_POINT:-/mnt/gentoo}"
        
        return 1
    fi
}

clear_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        if show_yesno "Are you sure you want to clear the saved configuration?"; then
            rm -f "$CONFIG_FILE"
            log_success "Configuration cleared"
        fi
    else
        show_info "No saved configuration to clear"
    fi
}

show_config_summary() {
    local summary="Current Configuration:\n\n"
    summary+="System Configuration:\n"
    summary+="  Init System: ${CONFIG[INIT_SYSTEM]:-Not set}\n"
    summary+="  Boot Mode: ${CONFIG[BOOT_MODE]:-Not set}\n"
    summary+="  Hostname: ${CONFIG[HOSTNAME]}\n"
    summary+="  Username: ${CONFIG[USERNAME]}\n"
    summary+="  Timezone: ${CONFIG[TIMEZONE]}\n\n"
    summary+="Disk Configuration:\n"
    summary+="  Install Disk: ${CONFIG[INSTALL_DISK]:-Not set}\n"
    summary+="  Filesystem: ${CONFIG[FILESYSTEM]:-Not set}\n"
    summary+="  Encryption: ${CONFIG[USE_ENCRYPTION]}\n"
    summary+="  Mount Point: ${CONFIG[MOUNT_POINT]}"
    
    show_msgbox "Configuration Summary" "$summary"
}
